### ISSUE TITLE
Bugs related to the silent options

### ISSUE THREAD

**Issue by mikeaalv** [NiklasPfister/CausalKinetiX-R#1]
Hi,

I find this method published on PNAS pretty interesting and tried it on my data. 

At the beginning, I was having wired error message:

```
Error in bsplineS(evalarg, breaks, norder, nderiv, returnMatrix) : 
  Knots do not span the values of X
```

It seems x in bssplineS is somewhat zero. Some debugs point me to the variable `times_new` in CausalKinetiX.modelranking. It seems it is only nonzero when either `silent=FALSE` or `show.plot=TRUE`. Set `Silent=TRUE` did fix it. However, I don't quite understand how the turnoff of message affect model performance. Can you help with it (and correct me if I'm wrong)?

I'm using the package version from CRAN. 

Thank you.
Best.
Yue

**Comment by mikeaalv** [comment]
The relevant block of code is here 

```
matres=readMat(paste0(dir,"CausalKinetiX_input.mat"))
D_anno=matres[["mat.anno"]]
D_all=matres[["mat.all"]]
time=as.numeric(matres[["timevec"]])
env=as.numeric(matres[["envvec"]])
para=list(max.preds=TRUE,expsize=2,#expected number of term
          interactions=TRUE,pen.degree=3,smooth.Y=TRUE,
          integrated.model=FALSE,#derivative based objective function
          screening=30,#screening predictor size
          silent=TRUE)

target=1
ck.fit<-CausalKinetiX(D_anno,time,env,target,pars=para)#
```

The error message is here

```
Error in bsplineS(evalarg, breaks, norder, nderiv, returnMatrix) : 
  Knots do not span the values of X
```

Sorry I cannot share my data. My data was set according to the help. `nrow(D_anno0)==length(env)` and the column of `D_anno` is time*features.

Let me know if you need more information.

**Comment by mikeaalv** [comment]
I also find if I shift time to start at 0 then there seems to be no problem any more. `time=time-min(time)`

**Comment by mikeaalv** [comment]
I figured out a simple way to reproduce the error with `generalate.data.maillard`

This block will produce error:
```
##reproduce time problem
simulation.obj <- generate.data.maillard(target=6,
                                         env=rep(1:3, 5),
                                         L=15,
                                         seed=5,
                                         par.noise=list(noise.sd=1))

D <- simulation.obj$simulated.data
time <- simulation.obj$time
env <- simulation.obj$env
target <- simulation.obj$target

## Fit data using CausalKinetiX
ck.fit <- CausalKinetiX(D, time+0.1, env, target,
                        pars=list(expsize=1,
                                  average.reps=TRUE))
# variable ranking (here the true parent is variable 4)
print(ck.fit$ranking)
```

The shift of time is reasonable as there is no reason the time of collect data start at 0.

This block will not produce error
```
simulation.obj <- generate.data.maillard(target=6,
                                         env=rep(1:3, 5),
                                         L=15,
                                         seed=5,
                                         par.noise=list(noise.sd=1))

D <- simulation.obj$simulated.data
time <- simulation.obj$time
env <- simulation.obj$env
target <- simulation.obj$target

## Fit data using CausalKinetiX
ck.fit <- CausalKinetiX(D, time+0.1, env, target,
                        pars=list(expsize=1,
                                  average.reps=TRUE,silent=FALSE))
# variable ranking (here the true parent is variable 4)
print(ck.fit$ranking)
```

**Comment by NiklasPfister** [comment]
Dear Yue,

thanks for pointing this out. There was a mistake in how the case silent=TRUE was handling things. It was an easy fix so I just pushed it. You can now install the current version from github and the problem should be solved.

Let me know if you run into any other issues.

Best,
Niklas.

**Comment by mikeaalv** [comment]
Thank you very much. I checked it and there is no more error.
